[package]
name = "nilepsilon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
float_eq = "1.0.0"
rand = "0.8.5"
rayon = "1.5.3"
rand_distr = "0.4.3"
